# Generated by Django 4.0.2 on 2022-05-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0002_apro_spec_mrp_element_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_transit',
            name='delivery_qty',
        ),
        migrations.AddField(
            model_name='mb52',
            name='descr_of_storage_loc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='stock_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
