# Generated by Django 4.0.2 on 2022-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0003_remove_stock_transit_delivery_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_transit',
            name='delivery_qty',
            field=models.FloatField(null=True),
        ),
    ]
