# Generated by Django 4.0.2 on 2022-05-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0004_stock_transit_delivery_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mb52',
            name='descr_of_storage_loc',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='stock_type',
        ),
    ]
