# Generated by Django 4.0.2 on 2022-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0005_remove_mb52_descr_of_storage_loc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb52',
            name='stock_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
