# Generated by Django 4.0.2 on 2022-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0006_mb52_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb52',
            name='descr_of_storage_loc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
