# Generated by Django 4.0.2 on 2022-05-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0007_mb52_descr_of_storage_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb52',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
