# Generated by Django 4.0.2 on 2022-05-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0008_mb52_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mb52',
            name='key',
        ),
    ]
