# Generated by Django 4.0.2 on 2022-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0010_art_mara_marc_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='art_mara_marc',
            name='purchasing_group_designation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
