# Generated by Django 4.0.2 on 2022-05-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0012_zpp_md_stock_delivery_qty_zpp_md_stock_num_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='zpp_md_stock',
            name='confirmed_quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='purchasing_group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='validated_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='vendor_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
