# Generated by Django 4.0.2 on 2022-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0014_remove_zpp_md_stock_confirmed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zpp_md_stock',
            name='take_into_account_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='take_into_account_fr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
