# Generated by Django 4.0.2 on 2022-05-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0015_zpp_md_stock_take_into_account_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='action_message',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='data_for_planning_element',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='plan_date',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='reorder_date',
        ),
    ]
