# Generated by Django 4.0.2 on 2022-05-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0016_remove_zpp_md_stock_action_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mb52',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='blocked_return_stock_value',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='blocked_stock_value',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='for_free_use',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='in_quality_control',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='non_free_stock',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='non_free_value',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='returns',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='store_level_deletion_indicator',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='transit_transfer',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='transit_transfer_value',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='value_quality_control',
        ),
    ]
