# Generated by Django 4.0.2 on 2022-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0017_remove_mb52_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mb52',
            name='blocked',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='blocked_return_stock_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='blocked_stock_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='currency',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='for_free_use',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='in_quality_control',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='non_free_stock',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='non_free_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='returns',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='store_level_deletion_indicator',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='transit_transfer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='transit_transfer_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='unit',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mb52',
            name='value_quality_control',
            field=models.FloatField(null=True),
        ),
    ]
