# Generated by Django 4.0.2 on 2022-05-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0019_remove_mb52_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mb52',
            name='descr_of_storage_loc',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='store',
        ),
    ]
