# Generated by Django 4.0.2 on 2022-05-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0020_remove_mb52_descr_of_storage_loc_remove_mb52_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mb52',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='mb52',
            name='uploaded_by',
        ),
    ]
