# Generated by Django 4.0.2 on 2022-05-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0024_zpp_md_stock_uploaded_at_zpp_md_stock_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='week',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='year',
        ),
    ]
