# Generated by Django 4.0.2 on 2022-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0025_remove_zpp_md_stock_week_remove_zpp_md_stock_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='zpp_md_stock',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
