# Generated by Django 4.0.2 on 2022-05-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0027_zpp_md_stock_input_need_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='mrp_element',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='vendor',
        ),
    ]
