# Generated by Django 4.0.2 on 2022-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0029_remove_stock_transit_taken_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_transit',
            name='division',
            field=models.IntegerField(null=True),
        ),
    ]
