# Generated by Django 4.0.2 on 2022-05-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0031_remove_zpp_md_stock_take_into_account_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zpp_md_stock',
            name='need_past',
            field=models.FloatField(null=True),
        ),
    ]
