# Generated by Django 4.0.2 on 2022-05-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0032_zpp_md_stock_need_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='delivery_qty',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='need_past',
        ),
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='num_parcel',
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='plan_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='week_number',
            field=models.IntegerField(null=True),
        ),
    ]
