# Generated by Django 4.0.2 on 2022-05-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0033_remove_zpp_md_stock_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zpp_md_stock',
            name='week_number',
        ),
        migrations.AddField(
            model_name='zpp_md_stock',
            name='year_week',
            field=models.IntegerField(null=True),
        ),
    ]
