# Generated by Django 4.0.2 on 2022-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0034_remove_zpp_md_stock_week_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zpp_md_stock',
            name='year_week',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
