# Generated by Django 4.0.4 on 2022-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0035_alter_zpp_md_stock_year_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_10',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_11',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_12',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_3',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_4',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_5',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_6',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_7',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_8',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='expected_stock_week_w_9',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
