# Generated by Django 4.0.4 on 2022-06-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0036_alter_zmm_carnet_cde_is_expected_stock_week_w_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmm_carnet_cde_is',
            name='quantity_to_receive',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
