# Generated by Django 4.0.4 on 2022-07-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortage', '0038_z_sc_m_0002_z_sc_p_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='zpp_md_stock',
            name='mrp_element',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
